optimizer: CD
stopcondition {
  all_processed: false
  steps: 100000
}
train: true
batchsize: 100
data_proto: "/media/DataDisk/dataset/data/mnist/mnist.pbtxt"
eval_after: 1000
checkpoint_after: 10000
checkpoint_directory: "/media/DataDisk/dataset/data/mnist/res"
randomize: true
show_after: 1000
