optimizer: GRADIENT_DESCENT
stopcondition {
  all_processed: false
  steps: 100000
}
train: true
batchsize: 100
data_proto: "/media/DataDisk/dataset/data/mnist/mnist.pbtxt"
eval_after: 500
checkpoint_after: 10000
checkpoint_directory: "/media/DataDisk/dataset/data/mnist/res"
randomize: true
verbose: true
